/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IgcInputGroup {}
  interface SampleComponent {}
}

declare global {


  interface HTMLIgcInputGroupElement extends Components.IgcInputGroup, HTMLStencilElement {}
  var HTMLIgcInputGroupElement: {
    prototype: HTMLIgcInputGroupElement;
    new (): HTMLIgcInputGroupElement;
  };

  interface HTMLSampleComponentElement extends Components.SampleComponent, HTMLStencilElement {}
  var HTMLSampleComponentElement: {
    prototype: HTMLSampleComponentElement;
    new (): HTMLSampleComponentElement;
  };
  interface HTMLElementTagNameMap {
    'igc-input-group': HTMLIgcInputGroupElement;
    'sample-component': HTMLSampleComponentElement;
  }
}

declare namespace LocalJSX {
  interface IgcInputGroup {}
  interface SampleComponent {}

  interface IntrinsicElements {
    'igc-input-group': IgcInputGroup;
    'sample-component': SampleComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'igc-input-group': LocalJSX.IgcInputGroup & JSXBase.HTMLAttributes<HTMLIgcInputGroupElement>;
      'sample-component': LocalJSX.SampleComponent & JSXBase.HTMLAttributes<HTMLSampleComponentElement>;
    }
  }
}


